### ISSUE TITLE
Intermediate Bulk Container (IBC)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aquaponics#19]
I intend to build our Aquaponics system using Intermediate Bulk Containers (IBCs)
https://en.wikipedia.org/wiki/Intermediate_bulk_container
![image](https://user-images.githubusercontent.com/194400/41903402-b0a079c2-792d-11e8-9639-cfa636bcade3.png)
E.g: https://youtu.be/FXPvf2oBT3Q

They can be stacked:
![image](https://user-images.githubusercontent.com/194400/41902222-d3843f8a-792a-11e8-9c5b-d048a0abb863.png)

Buying them Second Hand is usually quite cheap:
https://www.ebay.co.uk/itm/ibc-container-tank-1000ltr/173368860869
![ibc-second-hand-25](https://user-images.githubusercontent.com/194400/41904610-bcb19de2-7930-11e8-9ff0-5019946a83a2.png)
Or in PT:
https://www.olx.pt/anuncio/depositos-1000-l-para-agua-ou-outros-residuos-IDth6IA.html
![image](https://user-images.githubusercontent.com/194400/41901004-d31758aa-7927-11e8-9bc4-f4c1735b600f.png)

The only thing to be _aware_ (_careful_) of is asking/knowing _exactly_ which liquid was stored previously so we don't end up with "_unusable_" containers. We want IBCs that have have stored **water** or **food substances** ***not*** petrochemical products, solvents, detergents, or adhesives.

## Todo

+ [ ] Determine how many of these we need in order to build a **closed loop system** that
  + [ ] Receives "Greywater" as the input
  + [ ] Filters/Purifies the Greywater (_in as many stages as necessary_)
  + [ ] Passes pure water into one or more fish tanks where fish waste is accumulated 
  + [ ] Circulates ***nutrient-rich*** water through our plant-root system
  + [ ] Nutrient-spent water should be returned to the greywater tank

I'm going to buy a _couple_ of IBCs to build a **_basic_ Aquaponics System** and just start iterating.

**Comment by nelsonic** [comment]
I am in contact with a _local_ IBC seller on OLX:
https://www.olx.pt/anuncio/contentor-1000l-ibc-IDChoTU.html
![image](https://user-images.githubusercontent.com/194400/49458579-fe8c1e80-f7e4-11e8-854e-2cdd8d333c21.png)

![image](https://user-images.githubusercontent.com/194400/49458488-d0a6da00-f7e4-11e8-9ae1-f298a00030b0.png)

I'm _reluctant_ to give this rando my (_your_) Mobile number.
But will follow up when the Grey Water tank is ready for the IBCs.

**Comment by iteles** [comment]
That's likely to be a little while given that the attic is our current priority and that will likely take the builders up until Xmas to finish.

It might be worth getting in touch with him next week when we have a better idea of timelines for the property to be safe to store things in unless you think he has a lot of stock 👍

**Comment by nelsonic** [comment]
I have already contacted him and requested when we can visit his site.
Proposed either Thursday Afternoon or next Week Tuesday. 👍
